#!/bin/bash
cd /opt/eol_spider_demo
echo "开始无限循环爬取"
i=0
while true
do
    ((i=i+1));
    echo "开始第$i次爬取"
    scrapy crawl ResearchGateSpider -s JOBDIR=crawls/ResearchGateSpider-1
    #echo "已抓取文件数"
    #tree -i .scrapy/ | grep directories
    echo "切换ip"
    /usr/bin/changeip
    echo "休息3秒"
    sleep 3
    echo "检查网络状况..."
    while true
    do
      ping=`ping -c 3 www.baidu.com|awk 'NR==7 {print int($4)}'`
      if [ $ping -ne 0 ];then
          echo "连续ping通3次www.baidu.com，网络ok"
          break;
      fi
    done
done
